name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v4

      - name: Set up Node 🕹️
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Install ⚙️
        uses: pnpm/setup@v2
        with:
          cache: true

      - name: Build 🛠
        run: pnpm build

      - name: Lint 🤓
        run: pnpm lint
